import React from 'react';
import Container from '../components/layout/Container';
import Footer from '../components/elements/Footer';
import NavBar from '../components/elements/NavBar';

const TermsOfUsePage: React.FC = () => {
  return (
    <div>
      <NavBar />
      <div style={{ background: '#f9fafb', minHeight: '100vh', padding: '40px 0' }}>
        <Container>
          <div style={{
            background: '#fff',
            borderRadius: '12px',
            padding: '60px 40px',
            boxShadow: '0 4px 20px rgba(0,0,0,0.08)',
            maxWidth: '800px',
            margin: '0 auto'
          }}>
            <h1 style={{
              color: '#1f2937',
              fontSize: '36px',
              fontWeight: '700',
              marginBottom: '20px',
              textAlign: 'center'
            }}>
              Terms of Use
            </h1>
            
            <p style={{
              color: '#6b7280',
              fontSize: '16px',
              textAlign: 'center',
              marginBottom: '40px'
            }}>
              Last updated: January 26, 2025
            </p>

            <div style={{ color: '#374151', fontSize: '16px', lineHeight: '1.7' }}>
              <section style={{ marginBottom: '40px' }}>
                <p style={{ marginBottom: '16px' }}>
                  Please read these Terms of Use ("Terms", "Terms of Use") carefully before using the Resignation Letter Generator website (the "Service") operated by Resignation Letter Generator ("us", "we", or "our"). Your access to and use of the Service is conditioned on your acceptance of and compliance with these Terms. These Terms apply to all visitors, users, and others who access or use the Service.
                </p>
                <p style={{ marginBottom: '16px' }}>
                  By accessing or using the Service you agree to be bound by these Terms. If you disagree with any part of the terms then you may not access the Service.
                </p>
              </section>

              <section style={{ marginBottom: '40px' }}>
                <h2 style={{ color: '#1f2937', fontSize: '24px', fontWeight: '600', marginBottom: '16px' }}>
                  Use of the Resignation Letter Generator
                </h2>
                <p style={{ marginBottom: '16px' }}>
                  Our Resignation Letter Generator is provided as a free service to help individuals create professional resignation letters. You may use the letters generated by our service for various purposes including but not limited to:
                </p>
                <ul style={{ paddingLeft: '20px', marginBottom: '16px' }}>
                  <li style={{ marginBottom: '8px' }}>Creating formal resignation letters for employment purposes</li>
                  <li style={{ marginBottom: '8px' }}>Educational purposes and learning about professional communication</li>
                  <li style={{ marginBottom: '8px' }}>Template reference for writing your own resignation letters</li>
                  <li style={{ marginBottom: '8px' }}>Career transition planning and preparation</li>
                  <li style={{ marginBottom: '8px' }}>Professional development and workplace communication training</li>
                </ul>
              </section>

              <section style={{ marginBottom: '40px' }}>
                <h2 style={{ color: '#1f2937', fontSize: '24px', fontWeight: '600', marginBottom: '16px' }}>
                  Your Responsibilities
                </h2>
                <p style={{ marginBottom: '16px' }}>
                  When using our resignation letter generator, you agree to:
                </p>
                <ul style={{ paddingLeft: '20px', marginBottom: '16px' }}>
                  <li style={{ marginBottom: '8px' }}>Provide accurate information when customizing your resignation letter</li>
                  <li style={{ marginBottom: '8px' }}>Review and verify all content before submitting to your employer</li>
                  <li style={{ marginBottom: '8px' }}>Comply with your employment contract and company policies regarding resignation notice</li>
                  <li style={{ marginBottom: '8px' }}>Use the generated letters in accordance with applicable employment laws</li>
                  <li style={{ marginBottom: '8px' }}>Maintain professionalism and courtesy in all resignation communications</li>
                </ul>
              </section>

              <section style={{ marginBottom: '40px' }}>
                <h2 style={{ color: '#1f2937', fontSize: '24px', fontWeight: '600', marginBottom: '16px' }}>
                  Limitations on Use
                </h2>
                <p style={{ marginBottom: '16px' }}>
                  You agree not to use the Service:
                </p>
                <ul style={{ paddingLeft: '20px', marginBottom: '16px' }}>
                  <li style={{ marginBottom: '8px' }}>In any way that violates any applicable national or international law or regulation</li>
                  <li style={{ marginBottom: '8px' }}>To generate content that is defamatory, threatening, abusive, or otherwise inappropriate</li>
                  <li style={{ marginBottom: '8px' }}>To attempt to interfere with or disrupt the service or servers</li>
                  <li style={{ marginBottom: '8px' }}>For automated or excessive usage that may negatively impact the service for other users</li>
                  <li style={{ marginBottom: '8px' }}>To create resignation letters containing false or misleading information</li>
                  <li style={{ marginBottom: '8px' }}>For any commercial purpose without our prior written consent</li>
                </ul>
              </section>

              <section style={{ marginBottom: '40px' }}>
                <h2 style={{ color: '#1f2937', fontSize: '24px', fontWeight: '600', marginBottom: '16px' }}>
                  Privacy and Data Protection
                </h2>
                <p style={{ marginBottom: '16px' }}>
                  We are committed to protecting your privacy. All personal information you enter into our resignation letter generator is processed locally on your device and is not transmitted to or stored on our servers. Please review our Privacy Policy for detailed information about how we handle your data.
                </p>
                <div style={{
                  background: '#ecfdf5',
                  border: '1px solid #10b981',
                  borderRadius: '8px',
                  padding: '20px',
                  marginBottom: '20px'
                }}>
                  <h3 style={{ color: '#065f46', fontSize: '18px', fontWeight: '600', marginBottom: '8px' }}>
                    🔒 Privacy Guarantee
                  </h3>
                  <p style={{ color: '#047857', margin: 0 }}>
                    Your employment details, personal information, and resignation letter content remain completely private and are never stored on our servers.
                  </p>
                </div>
              </section>

              <section style={{ marginBottom: '40px' }}>
                <h2 style={{ color: '#1f2937', fontSize: '24px', fontWeight: '600', marginBottom: '16px' }}>
                  Intellectual Property
                </h2>
                <p style={{ marginBottom: '16px' }}>
                  The Service and its original content, features, templates, and functionality are and will remain the exclusive property of Resignation Letter Generator and its licensors. The Service is protected by copyright, trademark, and other laws.
                </p>
                <p style={{ marginBottom: '16px' }}>
                  The resignation letters you generate using our templates become your property. You retain full ownership and rights to the customized content you create, and you may use these letters for their intended professional purposes.
                </p>
              </section>

              <section style={{ marginBottom: '40px' }}>
                <h2 style={{ color: '#1f2937', fontSize: '24px', fontWeight: '600', marginBottom: '16px' }}>
                  Disclaimer and Limitations
                </h2>
                <p style={{ marginBottom: '16px' }}>
                  While we strive to provide professional and appropriate resignation letter templates, we make no guarantees regarding:
                </p>
                <ul style={{ paddingLeft: '20px', marginBottom: '16px' }}>
                  <li style={{ marginBottom: '8px' }}>The legal adequacy of generated letters for your specific employment situation</li>
                  <li style={{ marginBottom: '8px' }}>Compliance with your specific employment contract or company policies</li>
                  <li style={{ marginBottom: '8px' }}>The outcome or reception of your resignation by your employer</li>
                  <li style={{ marginBottom: '8px' }}>Employment law compliance in your jurisdiction</li>
                </ul>
                <p style={{ marginBottom: '16px' }}>
                  We strongly recommend reviewing your employment contract and consulting with HR or legal professionals when appropriate before submitting your resignation.
                </p>
              </section>

              <section style={{ marginBottom: '40px' }}>
                <h2 style={{ color: '#1f2937', fontSize: '24px', fontWeight: '600', marginBottom: '16px' }}>
                  Service Availability
                </h2>
                <p style={{ marginBottom: '16px' }}>
                  We strive to maintain the availability of our resignation letter generator, but we cannot guarantee uninterrupted access. The Service is provided "as is" and we reserve the right to modify, suspend, or discontinue the Service at any time without notice.
                </p>
              </section>

              <section style={{ marginBottom: '40px' }}>
                <h2 style={{ color: '#1f2937', fontSize: '24px', fontWeight: '600', marginBottom: '16px' }}>
                  Links to Other Websites
                </h2>
                <p style={{ marginBottom: '16px' }}>
                  Our Service may contain links to third-party websites or services that are not owned or controlled by Resignation Letter Generator. We have no control over, and assume no responsibility for, the content, privacy policies, or practices of any third-party websites or services.
                </p>
              </section>

              <section style={{ marginBottom: '40px' }}>
                <h2 style={{ color: '#1f2937', fontSize: '24px', fontWeight: '600', marginBottom: '16px' }}>
                  Changes to Terms
                </h2>
                <p style={{ marginBottom: '16px' }}>
                  We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material, we will try to provide at least 30 days notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion.
                </p>
                <p style={{ marginBottom: '16px' }}>
                  By continuing to access or use our Service after those revisions become effective, you agree to be bound by the revised terms.
                </p>
              </section>

              <section style={{ marginBottom: '40px' }}>
                <h2 style={{ color: '#1f2937', fontSize: '24px', fontWeight: '600', marginBottom: '16px' }}>
                  Contact Information
                </h2>
                <p style={{ marginBottom: '16px' }}>
                  If you have any questions about these Terms of Use or our resignation letter generator service, please contact us:
                </p>
                <div style={{
                  background: '#f3f4f6',
                  borderRadius: '8px',
                  padding: '20px',
                  marginBottom: '20px'
                }}>
                  <p style={{ margin: 0 }}>
                  dongshan1025@gmail.com
                  </p>
                </div>
              </section>

              <div style={{
                background: '#f0f9ff',
                border: '1px solid #0ea5e9',
                borderRadius: '8px',
                padding: '20px',
                textAlign: 'center'
              }}>
                <h3 style={{ color: '#0c4a6e', fontSize: '18px', fontWeight: '600', marginBottom: '8px' }}>
                  📋 Professional Resignation Made Simple
                </h3>
                <p style={{ color: '#075985', margin: 0 }}>
                  Our resignation letter generator is designed to help you maintain professionalism during your career transitions. Use it responsibly and in accordance with your employment obligations.
                </p>
              </div>
            </div>
          </div>
        </Container>
      </div>
      <Footer />
    </div>
  );
};

export default TermsOfUsePage;